# Generated by Django 5.0.1 on 2024-02-24 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_cart',
            name='ammount',
            field=models.PositiveBigIntegerField(null=True),
        ),
    ]
